### ISSUE TITLE
LAS to 3mx mesh

### ISSUE THREAD

**Issue by otofoto** [ProjSEED/lodToolkit#12]
Fantastic tool!!!
Would it be possible to generate mesh from LAS so it can be used in standard viewer?

**Comment by GitGaoXing** [comment]
No can do. Generating mesh from LAS requires complex algorithm. Such as Possion surface reconstruction. Then you need to simplify the mesh to generate LOD.

**Comment by otofoto** [comment]
Simplified Delaunay triangulation TIN model for terrain would also be ok.
But mesh simplifying could be replaced by triangulation of each LOD separately.
