### ISSUE TITLE
obj转osgb，没有纹理

### ISSUE THREAD

**Issue by Rogers34** [ProjSEED/lodToolkit#15]
您好，非常感谢您分享的优秀的项目。
我用您项目把obj转换成了osgb格式，但是出现了一个问题。
转换之后的文件没有纹理。
您知道这是什么原因吗？是我哪里没用对吗？
或者需要我改动哪些地方，才能生成有纹理的osgb。
在这里先谢谢您了！
![Screenshot from 2021-06-22 18-12-11](https://user-images.githubusercontent.com/28282833/122907771-0f421700-d386-11eb-8d89-5bb1b0286be7.png)
![Screenshot from 2021-06-22 18-13-08](https://user-images.githubusercontent.com/28282833/122907799-149f6180-d386-11eb-957e-e4205cf82359.png)

**Comment by GitGaoXing** [comment]
obj->osgb还不能正常工作，WIP
