### ISSUE TITLE
处理las点坐标本身为大坐标的情况

### ISSUE THREAD

**Issue by GitGaoXing** [ProjSEED/lodToolkit#6]
在考虑header的offset以外还应考虑减去第一个点的坐标

**Comment by sihonwei** [comment]
可以考虑用las的中心点作为offset [（min_x + max_x）/2, min_y + max_y）/2, min_z + max_z）/2 ]

**Comment by GitGaoXing** [comment]
有道理，我试试

**Comment by GitGaoXing** [comment]
按你方案改了一把
